/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BehaviorEvent {
  'id' : bigint,
  'timestamp' : Time,
  'details' : string,
  'caller' : Principal,
  'eventType' : string,
}
export interface FeedbackEntry {
  'id' : bigint,
  'feedback' : [] | [string],
  'timestamp' : Time,
  'caller' : Principal,
  'rating' : [] | [bigint],
}
export interface Inquiry {
  'id' : bigint,
  'customerName' : string,
  'serviceType' : ServiceType,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phoneNumber' : string,
}
export interface SearchEvent {
  'search' : string,
  'timestamp' : Time,
  'caller' : Principal,
}
export type ServiceType = { 'event' : null } |
  { 'wedding' : null } |
  { 'portrait' : null } |
  { 'outdoor' : null } |
  { 'product' : null } |
  { 'preWedding' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllBehaviorEvents' : ActorMethod<[], Array<BehaviorEvent>>,
  'getAllFeedback' : ActorMethod<[], Array<FeedbackEntry>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAverageRating' : ActorMethod<[], [] | [number]>,
  'getBehaviorEventsByType' : ActorMethod<[string], Array<BehaviorEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeedbackById' : ActorMethod<[bigint], [] | [FeedbackEntry]>,
  'getInquiriesByServiceType' : ActorMethod<[ServiceType], Array<Inquiry>>,
  'getInquiryById' : ActorMethod<[bigint], [] | [Inquiry]>,
  'getRecentBehaviorEvents' : ActorMethod<[bigint], Array<BehaviorEvent>>,
  'getRecentSearchEvents' : ActorMethod<[bigint], Array<SearchEvent>>,
  'getTopBehaviorEvents' : ActorMethod<[bigint], Array<[string, bigint]>>,
  'getTopSearchQueries' : ActorMethod<[bigint], Array<[string, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordBehaviorEvent' : ActorMethod<[string, string], bigint>,
  'recordSearchEvent' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitFeedback' : ActorMethod<[[] | [bigint], [] | [string]], bigint>,
  'submitInquiry' : ActorMethod<
    [ServiceType, string, string, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];